package com.android.purebilibili.feature.video.ui.overlay

data class MiniPlayerOverlayLayoutPolicy(
    val miniPlayerWidthDp: Int,
    val miniPlayerHeightDp: Int,
    val outerPaddingDp: Int,
    val headerHeightDp: Int,
    val cardCornerRadiusDp: Int,
    val cardShadowDp: Int,
    val cardElevationDp: Int,
    val dragTopInsetDp: Int,
    val dragBottomInsetDp: Int,
    val titleFontSp: Int,
    val titleStartPaddingDp: Int,
    val titleEndPaddingDp: Int,
    val headerButtonSizeDp: Int,
    val headerButtonIconSizeDp: Int,
    val headerButtonIconPaddingDp: Int,
    val headerButtonRowEndPaddingDp: Int,
    val headerButtonSpacingDp: Int,
    val controlsGradientHeightDp: Int,
    val centerPlayIconPaddingDp: Int,
    val centerPlayIconSizeDp: Int,
    val seekHintBottomPaddingDp: Int,
    val seekHintCornerRadiusDp: Int,
    val seekHintFontSp: Int,
    val seekHintHorizontalPaddingDp: Int,
    val seekHintVerticalPaddingDp: Int,
    val dragHintBottomPaddingDp: Int,
    val dragHintFontSp: Int,
    val progressBarHeightDp: Int,
    val stashedWidthDp: Int,
    val stashedHeightDp: Int,
    val stashedSideCornerExtraDp: Int,
    val stashedIconSizeDp: Int,
    val stashedShadowDp: Int
)

fun resolveMiniPlayerOverlayLayoutPolicy(
    widthDp: Int,
    isTv: Boolean
): MiniPlayerOverlayLayoutPolicy {
    if (isTv || widthDp >= 1600) {
        return MiniPlayerOverlayLayoutPolicy(
            miniPlayerWidthDp = 320,
            miniPlayerHeightDp = 180,
            outerPaddingDp = 16,
            headerHeightDp = 32,
            cardCornerRadiusDp = 18,
            cardShadowDp = 18,
            cardElevationDp = 14,
            dragTopInsetDp = 60,
            dragBottomInsetDp = 120,
            titleFontSp = 12,
            titleStartPaddingDp = 10,
            titleEndPaddingDp = 72,
            headerButtonSizeDp = 28,
            headerButtonIconSizeDp = 16,
            headerButtonIconPaddingDp = 6,
            headerButtonRowEndPaddingDp = 6,
            headerButtonSpacingDp = 4,
            controlsGradientHeightDp = 44,
            centerPlayIconPaddingDp = 12,
            centerPlayIconSizeDp = 30,
            seekHintBottomPaddingDp = 18,
            seekHintCornerRadiusDp = 12,
            seekHintFontSp = 13,
            seekHintHorizontalPaddingDp = 14,
            seekHintVerticalPaddingDp = 7,
            dragHintBottomPaddingDp = 8,
            dragHintFontSp = 10,
            progressBarHeightDp = 4,
            stashedWidthDp = 44,
            stashedHeightDp = 52,
            stashedSideCornerExtraDp = 12,
            stashedIconSizeDp = 22,
            stashedShadowDp = 10
        )
    }

    if (widthDp >= 840) {
        return MiniPlayerOverlayLayoutPolicy(
            miniPlayerWidthDp = 300,
            miniPlayerHeightDp = 168,
            outerPaddingDp = 14,
            headerHeightDp = 30,
            cardCornerRadiusDp = 17,
            cardShadowDp = 17,
            cardElevationDp = 13,
            dragTopInsetDp = 56,
            dragBottomInsetDp = 110,
            titleFontSp = 12,
            titleStartPaddingDp = 9,
            titleEndPaddingDp = 66,
            headerButtonSizeDp = 26,
            headerButtonIconSizeDp = 15,
            headerButtonIconPaddingDp = 5,
            headerButtonRowEndPaddingDp = 5,
            headerButtonSpacingDp = 3,
            controlsGradientHeightDp = 42,
            centerPlayIconPaddingDp = 11,
            centerPlayIconSizeDp = 29,
            seekHintBottomPaddingDp = 17,
            seekHintCornerRadiusDp = 10,
            seekHintFontSp = 12,
            seekHintHorizontalPaddingDp = 13,
            seekHintVerticalPaddingDp = 6,
            dragHintBottomPaddingDp = 7,
            dragHintFontSp = 10,
            progressBarHeightDp = 3,
            stashedWidthDp = 42,
            stashedHeightDp = 50,
            stashedSideCornerExtraDp = 10,
            stashedIconSizeDp = 21,
            stashedShadowDp = 9
        )
    }

    if (widthDp >= 600) {
        return MiniPlayerOverlayLayoutPolicy(
            miniPlayerWidthDp = 280,
            miniPlayerHeightDp = 157,
            outerPaddingDp = 12,
            headerHeightDp = 28,
            cardCornerRadiusDp = 16,
            cardShadowDp = 16,
            cardElevationDp = 12,
            dragTopInsetDp = 50,
            dragBottomInsetDp = 100,
            titleFontSp = 11,
            titleStartPaddingDp = 8,
            titleEndPaddingDp = 60,
            headerButtonSizeDp = 24,
            headerButtonIconSizeDp = 14,
            headerButtonIconPaddingDp = 5,
            headerButtonRowEndPaddingDp = 4,
            headerButtonSpacingDp = 2,
            controlsGradientHeightDp = 40,
            centerPlayIconPaddingDp = 10,
            centerPlayIconSizeDp = 28,
            seekHintBottomPaddingDp = 16,
            seekHintCornerRadiusDp = 8,
            seekHintFontSp = 12,
            seekHintHorizontalPaddingDp = 12,
            seekHintVerticalPaddingDp = 6,
            dragHintBottomPaddingDp = 6,
            dragHintFontSp = 9,
            progressBarHeightDp = 3,
            stashedWidthDp = 40,
            stashedHeightDp = 48,
            stashedSideCornerExtraDp = 8,
            stashedIconSizeDp = 20,
            stashedShadowDp = 8
        )
    }

    return MiniPlayerOverlayLayoutPolicy(
        miniPlayerWidthDp = 220,
        miniPlayerHeightDp = 130,
        outerPaddingDp = 12,
        headerHeightDp = 28,
        cardCornerRadiusDp = 16,
        cardShadowDp = 16,
        cardElevationDp = 12,
        dragTopInsetDp = 50,
        dragBottomInsetDp = 100,
        titleFontSp = 11,
        titleStartPaddingDp = 8,
        titleEndPaddingDp = 60,
        headerButtonSizeDp = 24,
        headerButtonIconSizeDp = 14,
        headerButtonIconPaddingDp = 5,
        headerButtonRowEndPaddingDp = 4,
        headerButtonSpacingDp = 2,
        controlsGradientHeightDp = 40,
        centerPlayIconPaddingDp = 10,
        centerPlayIconSizeDp = 28,
        seekHintBottomPaddingDp = 16,
        seekHintCornerRadiusDp = 8,
        seekHintFontSp = 12,
        seekHintHorizontalPaddingDp = 12,
        seekHintVerticalPaddingDp = 6,
        dragHintBottomPaddingDp = 6,
        dragHintFontSp = 9,
        progressBarHeightDp = 3,
        stashedWidthDp = 40,
        stashedHeightDp = 48,
        stashedSideCornerExtraDp = 8,
        stashedIconSizeDp = 20,
        stashedShadowDp = 8
    )
}
